#!/usr/bin/env bash

set -e

for _ in ag peco vim; do
  if ! which $_ >/dev/null 2>&1; then
    echo "You need to install $_ for running $(basename "$0")." >&2
    exit 1
  fi
done

SELECTED="$(ag $@ | peco --query "$LBUFFER")"
test -n "$SELECTED" && eval "vim $(echo $SELECTED | awk -F : '{print $1 " +" $2}')"
# vim: set ft=sh :
